### ISSUE TITLE
Handle 304 HTTP Status Code

### ISSUE THREAD

**Issue by crilofer** [JanGorman/Hippolyte#11]
Hi,

I'm trying to test a response using this http status code but it's not working. I don't know if it's possible to test that response `withStatusCode` = `304` or there are any errors on my code.

Many thanks.

**Comment by JanGorman** [comment]
Hi,

Sorry for the late reply – I was off on vacation when you wrote. Working with redirects such as `304` isn't an issue. What is your test asserting? If you have the project source, you can look for the following test method `testItStubsRedirectNetworkCall` that is there to verify that redirects are handled correctly. Hope that helps. Otherwise please share your test code.
